package com.system.karyawan.variable;

/**
* Application constant
* generated by initializr
*/
public class AppConstant {
    public enum StatusUser {
        REGISTER,
        ACTIVE,
        RESET
    }
}
